/***************************************************************************
 * 
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 * $Id: auto_color.js 9417 2012-05-28 07:24:48Z liyubei $ 
 * 
 **************************************************************************/
 
 
 
/**
 * auto_color.js ~ 2012/05/25 13:26:47
 * @author leeight(liyubei@baidu.com)
 * @version $Revision: 9417 $ 
 * @description 
 *  
 **/

function to_string(value) {
  var v = parseInt(value, 10);
  var s = v.toString(16);
  if (v <= 15) {
    return '0' + s;
  }
  return s;
}

function auto_color(max) {
  var colors = [];
  for(var i = 0; i < max; i ++) {
    var red = (0xFF + Math.random() * 0xFF) / 2;
    var green = (0xFF + Math.random() * 0xFF) / 2;
    var blue = (0xFF + Math.random() * 0xFF) / 2;
    colors.push('#' + to_string(red) + to_string(green) + to_string(blue));
  }
  return colors;
}

var max = 20;
var less = [
  '//auto generated by node tools/auto_color.js',
  '@import-once "jn-progress-bars.less";'
];
var colors = auto_color(max);
for(var i = 0; i < max - 1; i ++) {
  var code = 
  '.progress-k' + i + ' .bar {\n' +
  '  #gradient > .vertical(' + colors[i] + ', ' + colors[i + 1] + ');\n' +
  '}\n' +
  '.progress-k' + i + '.progress-striped .bar {\n' +
  '  #gradient > .striped(' + colors[i] + ');\n' +
  '}';
  less.push(code);
}
console.log(less.join('\n'));


















/* vim: set ts=4 sw=4 sts=4 tw=100 noet: */
