/***************************************************************************
 *
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 * $Id: module.js 10829 2012-08-01 10:22:26Z liyubei $
 *
 **************************************************************************/



/**
 * src/ad/mobile/showcase/module.js ~ 2012/08/01 10:59:25
 * @author leeight@gmail.com (leeight)
 * @version $Revision: 10829 $
 * @description
 * ad.mobile.showcase这个模块
 **/

goog.require('er.controller');
goog.require('jn.util');

goog.provide('ad.mobile.showcase.Fields');
goog.provide('ad.mobile.showcase.config');
goog.provide('ad.mobile.showcase.data');

/**
 * @const
 * @type {Object.<string, *>}
 */
ad.mobile.showcase.Fields = {
    // CODE HERE.
};

/**
 * @type {Object}
 * @const
 */
ad.mobile.showcase.config = {
    'action' : [
        // CODE HERE.
    ],

    'url' : {
        // CODE HERE.
    }
};
// Autogenerated at 2012/08/01 10:59:25
ad.mobile.showcase.config['action'].push({'location': '/ad/mobile/showcase/show_case', 'action': 'ad.mobile.showcase.ShowCase'});

/**
 * 后端数据访问接口
 * @type {Object.<string, function(string, Function, Function)>}.
 */
ad.mobile.showcase.data = jn.util.da_generator([
    // CODE HERE
]);

er.controller.addModule(ad.mobile.showcase);





















/* vim: set ts=4 sw=4 sts=4 tw=100: */
