(function(AD_CONFIG, LINKS, RT_CONFIG){
/*! Copyright 2013 Baidu Inc. All Rights Reserved. */
    var AD_CONFIG = {
        id: "ec-ma-89699",
        main_url: "http://www.baidu.com",
        zhidao: {
            title: "关于<em>索尼</em>的网友问答 百度知道",
            rcv_url: "http://zhidao.baidu.com/search?lm=0&rn=10&pn=0&fr=search&ie=gbk&word=%CB%F7%C4%E1",
            answer_tip: "共32条问答来自百度知道 - 上次更新： 2013-10-09",
            best_answer: "<em>索尼</em>问答涵盖索尼产品硬件配置,硬件知识,软件下载,软件知识,评测,购买注意事项和途径,电脑论坛等相关问题32个...更多<em>索尼</em>问答,尽在百度知道。",
            site: "http://zhidao.baidu.com/search?lm=...",
            date: "2013-10-31",
            options: [{
                rcv_url: "http://zhidao.baidu.com/question/529721870.html",
                text: "<em>索尼</em>手机好吗?",
                answer_count: 9,
                last_updated: "2013-03-05"
            }, {
                rcv_url: "http://zhidao.baidu.com/question/319369423.html",
                text: "<em>索尼</em>的实力到底有多强?",
                answer_count: 4,
                last_updated: "2011-09-14"
            }, {
                rcv_url: "http://zhidao.baidu.com/question/198711536289777325.html",
                text: "<em>索尼</em>很好吗?",
                answer_count: 5,
                last_updated: "2013-11-13"
            }],
            more_rcv_url: "http://zhidao.baidu.com/search?lm=0&rn=10&pn=0&fr=search&ie=gbk&word=%CB%F7%C4%E1"
        },
        tieba: {
            title: "<em>索尼</em>吧 百度贴吧",
            rcv_title_url: "http://tieba.baidu.com/sony?fr=ala0",
            logo: "http://ecma.bdimg.com/adtest/0de6e2df4a5c79d8f0d84f8401966e45.jpg",
            rcv_logo_url: "http://tieba.baidu.com/f?kw=%E7%B4%A2%E5%B0%BC&ie=utf-8&fr=wwwt",
            desc: "日本<em>索尼</em>公司是一家全球知名的大型综合性跨国企业集团...",
            account_number: "3万人",
            post_number: "78万",
            info_bars: [{
                info: "图片(1467)",
                rcv_url: "http://tieba.baidu.com/f?kw=sony&tp=1"
            }, {
                info: "精品贴(0)",
                rcv_url: "http://tieba.baidu.com/f/good?kw=sony"
            }],
            site: "http://tieba.baidu.com/sony?fr=ala0",
            date: "2013-10-31",
            options: [{
                rcv_url: "http://tieba.baidu.com/p/2749079372",
                text: "关于索爱WM600这款蓝牙耳机，用过的进",
                click_count: 24,
                reply_count: 6
            }, {
                rcv_url: "http://tieba.baidu.com/p/2746194486",
                text: "索尼移动电源10000毫安CP-F10L超薄聚合物！金色版本全新上市！",
                click_count: 204,
                reply_count: 68
            }, {
                rcv_url: "http://tieba.baidu.com/p/2749166913",
                text: "整理一下我拍的SONY产品~~",
                click_count: 219,
                reply_count: 78
            }],
            more_info: {
                rcv_url: "http://tieba.baidu.com/sony?fr=ala0",
                text: "查看更多<em>索尼</em>吧内容>>"
            }
        }
    };;
var Mustache="undefined"!==typeof module&&module.exports||{};
(function(p){function y(a){return String(a).replace(/&(?!\w+;)|[<>"']/g,function(a){return z[a]||a})}function w(a,b,e){if("."===a)return b[b.length-1];a=a.split(".");for(var c=a.length-1,d=a[c],f,g,s=b.length,n,r;s;){r=b.slice(0);g=b[--s];for(n=0;n<c;){g=g[a[n++]];if(null==g)break;r.push(g)}if(g&&"object"===typeof g&&d in g){f=g[d];break}}"function"===typeof f&&(f=f.call(r[r.length-1]));return null==f?e:f}function A(a,b,e,c){var d="";a=w(a,b);if(c){if(""===a||null==a||!1===a||"[object Array]"==={}.toString.call(a)&&
0===a.length)d+=e()}else if("[object Array]"==={}.toString.call(a)){var f=a.length;B(a,function(a,c){var g={"@index":c,_index:c+1,"@first":0===c,"@size":f,"@last":c===f-1,"@odd":1===(c&1),"@even":0===(c&1)},k;for(k in g)g.hasOwnProperty(k)&&(a[k]=g[k]);b.push(a);d+=e();for(k in g)g.hasOwnProperty(k)&&delete a[k];b.pop()})}else if("object"===typeof a)b.push(a),d+=e(),b.pop();else if("function"===typeof a)var g=b[b.length-1],d=d+(a.call(g,e(),function(a){return q(a,g)})||"");else a&&(d+=e());return d}
function x(a,b){b=b||{};for(var e=b.tags||p.tags,c=e[0],d=e[e.length-1],f=['var buffer = "";',"\nvar line = 1;","\ntry {",'\nbuffer += "'],g=[],s=!1,n=!1,r=function(){if(!s||n||b.space)g=[];else for(;g.length;)f.splice(g.pop(),1);n=s=!1},k=[],u,q,C,w=function(a){e=t(a).split(/\s+/);q=e[0];C=e[e.length-1]},x=function(a){f.push('";',u,'\nvar partial = partials["'+t(a)+'"];',"\nif (partial) {","\n  buffer += render(partial,stack[stack.length - 1],partials);","\n}",'\nbuffer += "')},v=function(a,d){var b=
t(a);if(""===b)throw Error("Section name may not be empty");k.push({name:b,inverted:d});f.push('";',u,'\nvar name = "'+b+'";',"\nvar callback = (function () {","\n  return function () {",'\n    var buffer = "";','\nbuffer += "')},y=function(a){v(a,!0)},z=function(a){a=t(a);var b=0!=k.length&&k[k.length-1].name;if(!b||a!=b)throw Error('Section named "'+a+'" was never opened');a=k.pop();f.push('";',"\n    return buffer;","\n  };","\n})();");a.inverted?f.push("\nbuffer += renderSection(name,stack,callback,true);"):
f.push("\nbuffer += renderSection(name,stack,callback);");f.push('\nbuffer += "')},A=function(a){f.push('";',u,'\nbuffer += lookup("'+t(a)+'",stack,"");','\nbuffer += "')},B=function(a){f.push('";',u,'\nbuffer += escapeHTML(lookup("'+t(a)+'",stack,""));','\nbuffer += "')},D=1,m,l,h=0,E=a.length;h<E;++h)if(a.slice(h,h+c.length)===c){h+=c.length;m=a.substr(h,1);u="\nline = "+D+";";q=c;C=d;s=!0;switch(m){case "!":h++;l=null;break;case "=":h++;d="="+d;l=w;break;case ">":h++;l=x;break;case "#":h++;l=v;
break;case "^":h++;l=y;break;case "/":h++;l=z;break;case "{":d="}"+d;case "&":h++;n=!0;l=A;break;default:n=!0,l=B}m=a.indexOf(d,h);if(-1===m)throw Error('Tag "'+c+'" was not closed properly');c=a.substring(h,m);l&&l(c);for(l=0;~(l=c.indexOf("\n",l));)D++,l++;h=m+d.length-1;c=q;d=C}else switch(m=a.substr(h,1),m){case '"':case "\\":n=!0;f.push("\\"+m);break;case "\r":break;case "\n":g.push(f.length);f.push("\\n");r();D++;break;default:/^\s*$/.test(m)?g.push(f.length):n=!0,f.push(m)}if(0!=k.length)throw Error('Section "'+
k[k.length-1].name+'" was not closed properly');r();f.push('";',"\nreturn buffer;","\n} catch (e) { throw {error: e, line: line}; }");d=f.join("").replace(/buffer \+= "";\n/g,"");b.debug&&("undefined"!=typeof console&&console.log?console.log(d):"function"===typeof print&&print(d));return d}function E(a,b){var e=x(a,b),c=new Function("view,partials,stack,lookup,escapeHTML,renderSection,render",e);return function(a,b){b=b||{};var g=[a];try{return c(a,b,g,w,y,A,q)}catch(e){throw Error(e.error+"\n"+e.line);
}}}function v(a,b){b=b||{};return E(a,b)}function q(a,b,e){return v(a)(b,e)}p.name="mustache.js";p.version="0.5.0-dev";p.tags=["{{","}}"];p.parse=x;p.compile=v;p.render=q;p.to_html=function(a,b,e,c){a=q(a,b,e);if("function"===typeof c)c(a);else return a};var B=function(a,b,e){for(var c=0,d=a.length;c<d;++c)b.call(e,a[c],c,a)},t=function(a){return null==a?"":String(a).replace(/(^[\s\xA0]+)|([\s\xA0]+$)/g,"")},z={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}})(Mustache);
;
var AD_TEMPLATE_CONTENT="<!-- target:AD_ad_widget_zhixin_zhidao -->\n<div class=\"ad-widget-zhixin ad-widget-zhixin-zhidao\">\n<div class=\"ec-title\">\n<a target=\"_blank\" href=\"{{{rcv_url}}}\" title2=\"zx_zhidao_title\">{{{title}}}</a>\n</div>\n<div class=\"ec-tip\">\n{{answer_tip}}\n</div>\n<div class=\"ec-answer\"><strong>\u6700\u4f73\u7b54\u6848\uff1a</strong>{{{best_answer}}}</div>\n<div class=\"ec-foot\">\n<div class=\"ec-site\">{{site}}</div>\n<div class=\"ec-date\">{{date}}</div>\n</div>\n<ul>\n{{#options}}\n<li>\n<a href=\"{{{rcv_url}}}\" target=\"_blank\" title2=\"\u95ee\u9898{{_index}}\">{{{text}}}</a>\n<span class=\"ec-ac\">{{answer_count}}\u4e2a\u56de\u7b54</span>\n<span class=\"ec-lu\">{{last_updated}}</span>\n</li>\n{{/options}}\n{{#more_rcv_url}}\n<li><a class=\"ec-more\" href=\"{{{more_rcv_url}}}\" target=\"_blank\" title2=\"\u66f4\u591a\u95ee\u9898\">\u66f4\u591a\u77e5\u9053\u76f8\u5173\u95ee\u9898&gt;&gt;</a></li>\n{{/more_rcv_url}}\n</ul>\n</div>\n<!-- target:AD_ad_widget_zhixin_tieba -->\n<div class=\"ad-widget-zhixin ad-widget-zhixin-tieba\">\n<div class=\"ec-title\">\n<a target=\"_blank\" href=\"{{{rcv_title_url}}}\">{{{title}}}</a>\n</div>\n<a class=\"ec-logo\" href=\"{{{rcv_logo_url}}}\" target=\"_blank\"  title2=\"logo\"><img src=\"{{logo}}\"></a>\n<div class=\"ec-desc\">\n{{{desc}}}<br>\n\u6708\u6d3b\u8dc3\u7528\u6237\uff1a<span>{{account_number}}</span> \u7d2f\u8ba1\u53d1\u5e16\uff1a<span>{{post_number}}</span><br>\n{{#info_bars}}\n<a href=\"{{{rcv_url}}}\" target=\"_blank\" title2=\"{{info}}\">{{info}}</a>\n{{^@last}}<span class=\"ec-seperator\">|</span>{{/@last}}\n{{/info_bars}}\n</div>\n<ul class=\"ec-tieba\">\n{{#options}}\n<li>\n<a href=\"{{{rcv_url}}}\" target=\"_blank\" title2=\"\u5e16\u5b50{{_index}}\">{{{text}}}</a>\n<span class=\"ec-ac\">\u70b9\u51fb\uff1a{{click_count}}</span>\n<span class=\"ec-lu\">\u56de\u590d\uff1a{{reply_count}}</span>\n</li>\n{{/options}}\n{{#more_info}}\n<li><a class=\"ec-more\" href=\"{{{rcv_url}}}\" target=\"_blank\" title2=\"\u66f4\u591a\u95ee\u9898\">{{{text}}}</a></li>\n{{/more_info}}\n</ul>\n<ul class=\"ec-foot\">\n<li>{{site}}</li>\n<li>{{date}}</li>\n</ul>\n</div>\n";;
var AD_STYLE_CONTENT=".ad-widget-zhixin-zhidao{font:13px/1.5 arial,sans-serif}.ad-widget-zhixin-zhidao em{color:#c00;font-style:normal}.ad-widget-zhixin-zhidao .ec-title{font-size:16px}.ad-widget-zhixin-zhidao .ec-tip{color:#666;margin-top:3px}.ad-widget-zhixin-zhidao .ec-answer{margin-top:2px}.ad-widget-zhixin-zhidao .ec-answer strong{color:#666;font-weight:normal}.ad-widget-zhixin-zhidao .ec-foot{color:#008000;*zoom:1}.ad-widget-zhixin-zhidao .ec-foot:before,.ad-widget-zhixin-zhidao .ec-foot:after{display:table;content:\"\"}.ad-widget-zhixin-zhidao .ec-foot:after{clear:both}.ad-widget-zhixin-zhidao .ec-site,.ad-widget-zhixin-zhidao .ec-date{float:left;margin-right:10px}.ad-widget-zhixin-zhidao ul{margin:0;padding:0;list-style:none;margin-left:16px;margin-top:5px}.ad-widget-zhixin-zhidao li{*zoom:1}\n.ad-widget-zhixin-zhidao li:before,.ad-widget-zhixin-zhidao li:after{display:table;content:\"\"}.ad-widget-zhixin-zhidao li:after{clear:both}.ad-widget-zhixin-zhidao li a{display:block;width:280px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-decoration:none}.ad-widget-zhixin-zhidao li a,.ad-widget-zhixin-zhidao li span{float:left}.ad-widget-zhixin-zhidao li span{color:#666;width:80px}.ad-widget-zhixin-zhidao .ec-more{color:#7978c6}.ad-widget-zhixin-tieba{font:13px/1.5 arial,sans-serif;overflow:hidden;zoom:1}.ad-widget-zhixin-tieba em{color:#c00;font-style:normal}.ad-widget-zhixin-tieba ul{margin:0;padding:0;list-style:none;margin:0 0 0 10px}.ad-widget-zhixin-tieba .ec-title{margin-bottom:10px}.ad-widget-zhixin-tieba .ec-title a{font-size:16px}\n.ad-widget-zhixin-tieba .ec-logo{outline:0;border:0;float:left}.ad-widget-zhixin-tieba .ec-logo img{margin-top:2px;width:52px;height:52px}.ad-widget-zhixin-tieba .ec-desc{margin-left:65px}.ad-widget-zhixin-tieba .ec-desc span{display:inline-block;font-weight:bold;margin-right:20px;color:#333}.ad-widget-zhixin-tieba .ec-desc .ec-seperator{display:inline-block;padding:2px 10px;margin:0;height:15px}.ad-widget-zhixin-tieba .ec-tieba{clear:both;margin:0 0 0 16px}.ad-widget-zhixin-tieba .ec-tieba a{display:block;width:280px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-decoration:none}.ad-widget-zhixin-tieba .ec-tieba a,.ad-widget-zhixin-tieba .ec-tieba span{float:left}.ad-widget-zhixin-tieba .ec-tieba span{color:#666;width:80px}.ad-widget-zhixin-tieba .ec-more{color:#7978c6}.ad-widget-zhixin-tieba .ec-foot{clear:both;color:#008000}\n.ad-widget-zhixin-tieba .ec-foot li{float:left;margin-right:10px}#canvas .layout{padding:0 10px}#canvas .ad-block-0-0{padding-top:4px}#canvas .ad-block-0-1{padding-top:13px}";;
var baidu={version:"1.5.0"};baidu.guid="$BAIDU$";window[baidu.guid]=window[baidu.guid]||{};baidu.abstractMethod=function(){throw Error("unimplemented abstract method")};baidu.dom=baidu.dom||{};baidu.dom.g=function(a){if("string"==typeof a||a instanceof String){return document.getElementById(a)}else{if(a&&a.nodeName&&(a.nodeType==1||a.nodeType==9)){return a}}return null};baidu.g=baidu.G=baidu.dom.g;baidu.fn=baidu.fn||{};baidu.fn.blank=function(){};baidu.dom.show=function(a){a=baidu.dom.g(a);a.style.display="";return a};baidu.show=baidu.dom.show;baidu.object=baidu.object||{};baidu.extend=baidu.object.extend=function(c,a){for(var b in a){if(a.hasOwnProperty(b)){c[b]=a[b]}}return c};baidu.lang=baidu.lang||{};baidu.lang.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)
};baidu.array=baidu.array||{};baidu.each=baidu.array.forEach=baidu.array.each=function(g,e,b){var d,f,c,a=g.length;if("function"==typeof e){for(c=0;c<a;c++){f=g[c];d=e.call(b||g,f,c);if(d===false){break}}}return g};baidu.lang.isString=function(a){return"[object String]"==Object.prototype.toString.call(a)};baidu.isString=baidu.lang.isString;baidu.string=baidu.string||{};(function(){var a=new RegExp("(^[\\s\\t\\xa0\\u3000]+)|([\\u3000\\xa0\\s\\t]+\x24)","g");baidu.string.trim=function(b){return String(b).replace(a,"")}})();baidu.trim=baidu.string.trim;baidu.string.escapeReg=function(a){return String(a).replace(new RegExp("([.*+?^=!:\x24{}()|[\\]/\\\\])","g"),"\\\x241")};baidu.dom.q=function(h,e,b){var j=[],d=baidu.string.trim,g,f,a,c;if(!(h=d(h))){return j}if("undefined"==typeof e){e=document
}else{e=baidu.dom.g(e);if(!e){return j}}b&&(b=d(b).toUpperCase());if(e.getElementsByClassName){a=e.getElementsByClassName(h);g=a.length;for(f=0;f<g;f++){c=a[f];if(b&&c.tagName!=b){continue}j[j.length]=c}}else{h=new RegExp("(^|\\s)"+baidu.string.escapeReg(h)+"(\\s|\x24)");a=b?e.getElementsByTagName(b):(e.all||e.getElementsByTagName("*"));g=a.length;for(f=0;f<g;f++){c=a[f];h.test(c.className)&&(j[j.length]=c)}}return j};baidu.q=baidu.Q=baidu.dom.q;baidu.dom.hasAttr=function(c,b){c=baidu.g(c);var a=c.attributes.getNamedItem(b);return !!(a&&a.specified)};baidu.lang.inherits=function(g,e,d){var c,f,a=g.prototype,b=new Function();b.prototype=e.prototype;f=g.prototype=new b();for(c in a){f[c]=a[c]}g.prototype.constructor=g;g.superClass=e.prototype;if("string"==typeof d){f._className=d}};baidu.inherits=baidu.lang.inherits;;
var g=g||{};g.global=this;g.A=!0;g.C="en";g.B=!0;g.w=function(a){return void 0!==a};g.v=function(a,b,c){a=a.split(".");c=c||g.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.w(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};g.I=function(a,b,c){g.v(a,b,c)};g.H=function(a,b,c){a[b]=c};g.M=function(){return!1};g.N=function(){};g.L=function(){};function h(a,b){for(var c=a.split("."),d=b||window,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d}function l(a,b){function c(a,e){baidu.lang.isArray(a)?baidu.each(a,function(a,b){c(a,e.concat([b]))}):b(a,e)}c(a,[])};function m(){this.r={}}m.prototype.get=function(a){return this.r[a]||""};
m.prototype.parse=function(a){function b(a){return I.test(a)?b(a.replace(I,function(a,b){return q[b]||B[b]||""})):a}function c(a){a&&p&&C.push(a)}function d(){p&&(p in q?alert("Template: "+p+" is exist"):q[p]=C.join("\n"));p=null}a=a.split(/\r?\n/);for(var e=a.length,f=0,u=/\x3c!--\s*target:\s*([a-zA-Z0-9_]+)\s*--\x3e/,J=/\x3c!--\s*\/target\s*--\x3e/,I=/\x3c!--\s*import:\s*([a-zA-Z0-9_\/]+)\s*--\x3e/,K=/\x3c!--\s*scope:\s*([a-zA-Z0-9_]+)\s*--\x3e/,R=/\x3c!--\/scope--\x3e/,r,k,n,v,B=this.r,C=[],p,
q={};f<e;f++)k=a[f],0>=k.length||(u.lastIndex=-1,K.lastIndex=-1,(n=K.exec(k))?v=n[1]:(n=R.exec(k))?v=void 0:(n=u.exec(k))?(n=v?v+"/"+n[1]:n[1],k=k.split(u),c(k[0]),d(),C=[],p=n,c(k[2])):J.test(k)?(k=k.split(J),c(k[0]),d()):c(k));d();for(r in q)B[r]&&alert("Template: "+r+" already exists!"),B[r]=b(q[r])};var s=new m;function t(){};function w(){this.a={}}baidu.inherits(w,t);w.prototype.addListener=function(a,b){this.a[a]||(this.a[a]=[]);this.a[a].push(b)};w.prototype.dispose=function(){this.a={}};w.prototype.trigger=function(a,b){if(!this.a[a])return!0;var c,d=Array.prototype.slice.call(arguments,1),e=!0;for(c=0;c<this.a[a].length;c++){var f=this.a[a][c];f&&!1===f.apply(this,d)&&(e=!1)}return e};var x;function y(a){this.a={};this.h="ad-w-"+Math.floor(2147483648*Math.random()).toString(36);this.setData(a)}baidu.inherits(y,w);x=function(a,b){return Mustache.render(a,b)};y.prototype.trigger=function(a,b){if(!this.a[a])return!0;var c;c=this.a[a].length;var d=Array.prototype.slice.call(arguments,1),e=!0;for(c-=1;0<=c;c--){var f=this.a[a][c];if(f&&!1===f.apply(this,d)){e=!1;break}}return e};
y.prototype.getMainHtml=function(){if(!this.j||!this.f)throw Error("Widget's view and data can not be undefined.");var a=this,b=s.get(this.j),c=baidu.extend(this.f,{_id:function(){return function(b){return a.getId(b)}}});return x(b,c)};y.prototype.render=function(){var a=this.getRoot();if(a){var b=this.getMainHtml();a.innerHTML=b}};y.prototype.init=baidu.fn.blank;y.prototype.l=baidu.fn.blank;y.prototype.k=baidu.fn.blank;y.prototype.setData=function(a){a&&(this.f=baidu.object.extend(this.D||{},a))};
y.prototype.getRoot=function(){return baidu.g(this.getId())};y.prototype.getId=function(a){return a?this.h+"-"+a:this.h};y.prototype.show=function(){var a=this.getRoot();a&&baidu.show(a)};y.prototype.sendLog=function(a,b){baidu.lang.isString(a)?this.trigger("sendlog",{action:a,xp:b||a}):this.trigger("sendlog",a)};y.prototype.dispose=function(){var a=this.getRoot();a&&(a.innerHTML="",a.parentNode.removeChild(a))};function z(a){y.call(this,a);this.j="AD_ad_widget_zhixin_zhidao"}baidu.inherits(z,y);function D(a){this.s=a}D.prototype.start=function(a,b){!b&&this.n&&this.n.dispose();return this.n=this.s(!!a)};D.prototype.set=function(a,b){"AD_CONFIG"===a?AD_CONFIG=b:"LINKS"===a?LINKS=b:"RT_CONFIG"===a&&(RT_CONFIG=b)};D.prototype.get=function(a){if("AD_CONFIG"===a)return AD_CONFIG;if("LINKS"===a)return LINKS;if("RT_CONFIG"===a)return RT_CONFIG;if("AD_STYLE_CONTENT"===a)return AD_STYLE_CONTENT};function E(a){y.call(this,a);this.j="AD_ad_widget_zhixin_tieba"}baidu.inherits(E,y);function F(){}F.prototype.m=baidu.abstractMethod;F.prototype.p=baidu.abstractMethod;function G(a){this.t=baidu.object.extend({block_class:"ad-layout-block"},a||{})}baidu.inherits(G,F);G.prototype.m=function(a){var b=H(this,a),c={};l(a,function(a,b){var f=a.getMainHtml();c["block-"+b.join("-")+"-id"]=a.getId();c["block_"+b.join("_")]=f});return Mustache.render(b,c)};G.prototype.p=function(a,b){l(a,function(a,d){for(var e=b,f=0;e&&f<d.length;f++)e=e.children[d[f]];if(!e)throw Error("Invalid pre-rendered html formated.");a.h=e.id})};
function H(a,b){var c=[];baidu.each(b,function(b,e){c.push(L(a,b,[e]))});return c.join("\n")}function L(a,b,c){var d=">";baidu.lang.isArray(b)||(d=' id="{{=<% %>=}}{{block-<% indexes %>-id}}">');var e=[Mustache.render('<div class="{{block_class}} {{block_class}}-{{indexes}}"'+d,{block_class:a.t.block_class,indexes:c.join("-")})];baidu.lang.isArray(b)?baidu.each(b,function(b,d){e.push(L(a,b,c.concat([d])))}):e.push("{{{block_"+c.join("_")+"}}}");e.push("</div>");return e.join("\n")};function M(a,b){y.call(this,a);this.d=new G({block_class:"ad-block"});this.c=[];this.u=b||""}baidu.inherits(M,y);M.prototype.setWidgets=function(a){this.c=[].slice.call(arguments)};M.prototype.getWidget=function(a){var b=Array.prototype.slice.call(arguments);if(!b.length)return null;var c=this.c[b[0]];if(!c)return null;for(var d=1;d<b.length;d++)if(c=c[b[d]],null==c)return null;return c};M.prototype.getMainHtml=function(){this.f._content=this.d.m(this.c);return M.superClass.getMainHtml.call(this)};
M.prototype.forEach=function(a){l(this.c,a)};function N(a,b){b.addListener("sendlog",function(b){b.action=(a.u||"")+b.action;a.sendLog(b)})}M.prototype.init=function(){this.forEach(function(a){a.init()})};M.prototype.l=function(){this.forEach(function(a){a.l()})};M.prototype.k=function(){this.forEach(function(a){a.k()});var a=this;this.forEach(function(b){N(a,b)})};M.prototype.dispose=function(){this.forEach(function(a){a.dispose()})};function O(){}O.prototype.attachTo=function(){};function P(a){RT_CONFIG.__plugins||(RT_CONFIG.__plugins=[]);RT_CONFIG.__plugins.push(a)};var Q={getContext:function(a){return h("ECOM_MA_LEGO.materials."+a)},J:function(a){a=a||Q.getId();return(a=Q.getContext(a))?a.material||null:null},getId:function(){var a="canvas";"undefined"!=typeof RT_CONFIG&&RT_CONFIG.id?a=RT_CONFIG.id:"undefined"!=typeof AD_CONFIG&&AD_CONFIG.id&&(a=AD_CONFIG.id);return a},F:function(a){var b=("ECOM_MA_LEGO.materials."+a.material.getId()).split("."),c=window;b[0]in c||!c.execScript||c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)b.length||void 0===
a?c=c[d]?c[d]:c[d]={}:c[d]=a},K:function(a){var b=a.getRoot();for(a=document;b&&b!=a;){if(baidu.dom.hasAttr(b,"data-rendered"))return b.id;b=b.parentNode}return null}};function S(){}baidu.inherits(S,O);P(new S);S.prototype.attachTo=function(a){a.addListener("aftermaterialshow",function(){var a=Q.getId()+";"+(window.bdQuery||"");if(a=/m(\d+)_canvas/.exec(a)){var a=a[1],c="m"+a+"_BEGIN",d="m"+a+"_END";"number"===typeof window[c]&&"number"===typeof window[d]&&((new Image).src="http://www.baidu.com/nocache/fesplg/s.gif?product_id=45&page_id=901&adv_id="+encodeURIComponent(a)+"&time="+(window[d]-window[c])+"&_t="+Math.random())}})};function U(){}baidu.inherits(U,O);P(new U);U.prototype.attachTo=function(a){a.addListener("aftermaterialshow",function(){var b=h("global.background",AD_CONFIG);if(b){var c=baidu.q("ad-material-inside",a.getRoot());c&&c.length?c[0].style.backgroundImage="url("+b+")":a.getRoot().style.backgroundImage="url("+b+")"}})};function V(a){M.call(this,{});this.d=new G({block_class:"ad-block"});this.b=a||Q.getId();this.o="ad-style-"+this.b;if("undefined"!==typeof RT_CONFIG&&(a=RT_CONFIG.__plugins)&&a.length)for(var b=0;b<a.length;b++)a[b].attachTo(this)}baidu.inherits(V,M);V.prototype.getRoot=function(){baidu.g(this.b)||document.write('<div id="'+this.b+'"></div>');return baidu.g(this.b)};V.prototype.getId=function(){return this.b};V.prototype.getMainHtml=function(){return'<div class="layout">'+this.d.m(this.c)+"</div>"};
V.prototype.init=function(){var a=this.getRoot();if(a){if("string"===typeof AD_TEMPLATE_CONTENT&&/AD_ad_widget_siva_/.test(AD_TEMPLATE_CONTENT))try{this.d.p(this.c,a.children[0])}catch(b){a.innerHTML=this.getMainHtml()}else a.innerHTML=this.getMainHtml();a.setAttribute("data-rendered","true")}V.superClass.init.call(this)};
V.prototype.show=function(){try{this.trigger("beforematerialshow")}catch(a){}if("undefined"!==typeof AD_STYLE_CONTENT&&!baidu.g(this.o)){var b=AD_STYLE_CONTENT.replace(/#canvas/g,"#"+this.b),c=this.o,d=this.getRoot(),e=d.parentNode;if(e){var f=document.createElement("style");f.type="text/css";f.media="screen";c&&(f.id=c);e.insertBefore(f,d);f.styleSheet?f.styleSheet.cssText=b:f.appendChild(document.createTextNode(b))}}this.init();this.l();this.k();baidu.show(this.getId());try{this.trigger("aftermaterialshow")}catch(u){}};
V.prototype.dispose=function(){V.superClass.dispose.call(this);var a=this.getRoot();a&&(a.innerHTML="")};(function(a){s.parse(AD_TEMPLATE_CONTENT);"function"===typeof ECMA_define?ECMA_define(function(){return new D(a)}):a()})(function(a){var b=new z(AD_CONFIG.zhidao),c=new E(AD_CONFIG.tieba),b=[b,c],c=new V;c.setWidgets(b);if(!0===a)return c;c.show()});

})(/** AD_CONFIG */{}, /** LINKS */[], /** RT_CONFIG */{});