#!/usr/bin/env python
#!-*- coding:utf-8 -*-
#!vim: set ts=4 sw=4 sts=4 tw=100:
# ***************************************************************************
# 
# Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
# $Id: gen.py 10214 2012-07-12 11:10:04Z songao $ 
# 
# **************************************************************************/
 
 
 
import os
import sys
import optparse
 
__author__ = 'leeight <liyubei@baidu.com>'
__date__ = '2012/07/11 14:42:12'
__revision = '$Revision: 10214 $'


def RCV(url = None):
  return "%%%%BEGIN_LINK%%%%url=%s\x01urlid=0%%%%END_LINK%%%%" % (url or "http://www.baidu.com/")

KUBA_LOGO_URL = "http://eiv.baidu.com/juejin/kuba/logo.png"
FANKE_LOGO_URL = "http://eiv.baidu.com/juejin/vancl/test/LOGO_fanke2.png"

DATA = [
  # kuba - query
  {
    "output_file_name" : "kuba-a123-query",
    "logo_url" : RCV("http://www.coo8.com/product/186077.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1A1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "三星手机 GT-S5830i 玛瑙黑",
    "product_0_url" : RCV("http://www.coo8.com/product/186077.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1A1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A1.png",
    "product_0_price" : "1488",
    "product_1_name" : "华为手机 T8100 黑色",
    "product_1_url" : RCV("http://www.coo8.com/product/217081.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1A2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A2.png",
    "product_1_price" : "429",
    "product_2_name" : "联想手机双卡双待A520 玄武灰",
    "product_2_url" : RCV("http://www.coo8.com/product/208053.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1A3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A3.png",
    "product_2_price" : "1399",
  },
  {
    "output_file_name" : "kuba-b123-query",
    "logo_url" : RCV("http://www.coo8.com/product/176994.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1B1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "ThinkPad 笔记本电脑 E40",
    "product_0_url" : RCV("http://www.coo8.com/product/176994.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1B1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B1.png",
    "product_0_price" : "2699",
    "product_1_name" : "索尼笔记本电脑 VPCEG36EC/W",
    "product_1_url" : RCV("http://www.coo8.com/product/168743.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1B2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B2-1.png",
    "product_1_price" : "3398",
    "product_2_name" : "华硕（ASUS）14英寸笔记本电脑",
    "product_2_url" : RCV("http://www.coo8.com/product/210229.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1B3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B3-1.png",
    "product_2_price" : "2499",
  },
  {
    "output_file_name" : "kuba-c123-query",
    "logo_url" : RCV("http://www.coo8.com/product/148613.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1C1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "索尼微单套机 NEX-5NK 银色",
    "product_0_url" : RCV("http://www.coo8.com/product/148613.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1C1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C1.png",
    "product_0_price" : "4299",
    "product_1_name" : "卡西欧数码相机 EX-ZR100 白色",
    "product_1_url" : RCV("http://www.coo8.com/product/143115.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1C2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C2.png",
    "product_1_price" : "1499",
    "product_2_name" : "佳能单反数码相机EOS 600D",
    "product_2_url" : RCV("http://www.coo8.com/product/122217.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1C3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C3.png",
    "product_2_price" : "4567",
  },
  {
    "output_file_name" : "kuba-d123-query",
    "logo_url" : RCV("http://www.coo8.com/product/201251.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1D1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "三星 40英寸LED液晶电视",
    "product_0_url" : RCV("http://www.coo8.com/product/201251.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1D1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D1.png",
    "product_0_price" : "3598",
    "product_1_name" : "夏普 52英寸LED液晶电视 黑色",
    "product_1_url" : RCV("http://www.coo8.com/product/125618.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1D2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D2.png",
    "product_1_price" : "6888",
    "product_2_name" : "康佳32英寸蓝光LED液晶电视",
    "product_2_url" : RCV("http://www.coo8.com/product/191527.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1D3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D3.png",
    "product_2_price" : "1798",
  },
  {
    "output_file_name" : "kuba-e123-query",
    "logo_url" : RCV("http://www.coo8.com/product/133194.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1E1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "伊莱克斯静雅 挂式空调 白色",
    "product_0_url" : RCV("http://www.coo8.com/product/133194.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1E1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E1.png",
    "product_0_price" : "1899",
    "product_1_name" : "奥克斯智家能系列柜式定频空调",
    "product_1_url" : RCV("http://www.coo8.com/product/180868.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1E2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E2.png",
    "product_1_price" : "4999",
    "product_2_name" : "格力U酷系列挂式变频空调 银色",
    "product_2_url" : RCV("http://www.coo8.com/product/130088.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian1E3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E3.png",
    "product_2_price" : "3599",
  },
  # kuba - plsa
  {
    "output_file_name" : "kuba-a123-plsa",
    "logo_url" : RCV("http://www.coo8.com/product/186077.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2A1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "三星手机 GT-S5830i 玛瑙黑",
    "product_0_url" : RCV("http://www.coo8.com/product/186077.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2A1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A1.png",
    "product_0_price" : "1488",
    "product_1_name" : "华为手机 T8100 黑色",
    "product_1_url" : RCV("http://www.coo8.com/product/217081.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2A2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A2.png",
    "product_1_price" : "429",
    "product_2_name" : "联想手机双卡双待A520 玄武灰",
    "product_2_url" : RCV("http://www.coo8.com/product/208053.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2A3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/A3.png",
    "product_2_price" : "1399",
  },
  {
    "output_file_name" : "kuba-b123-plsa",
    "logo_url" : RCV("http://www.coo8.com/product/176994.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2B1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "ThinkPad 笔记本电脑 E40",
    "product_0_url" : RCV("http://www.coo8.com/product/176994.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2B1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B1.png",
    "product_0_price" : "2699",
    "product_1_name" : "索尼笔记本电脑 VPCEG36EC/W",
    "product_1_url" : RCV("http://www.coo8.com/product/168743.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2B2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B2-1.png",
    "product_1_price" : "3398",
    "product_2_name" : "华硕（ASUS）14英寸笔记本电脑",
    "product_2_url" : RCV("http://www.coo8.com/product/210229.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2B3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/B3-1.png",
    "product_2_price" : "2499",
  },
  {
    "output_file_name" : "kuba-c123-plsa",
    "logo_url" : RCV("http://www.coo8.com/product/148613.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2C1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "索尼微单套机 NEX-5NK 银色",
    "product_0_url" : RCV("http://www.coo8.com/product/148613.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2C1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C1.png",
    "product_0_price" : "4299",
    "product_1_name" : "卡西欧数码相机 EX-ZR100 白色",
    "product_1_url" : RCV("http://www.coo8.com/product/143115.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2C2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C2.png",
    "product_1_price" : "1499",
    "product_2_name" : "佳能单反数码相机EOS 600D",
    "product_2_url" : RCV("http://www.coo8.com/product/122217.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2C3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/C3.png",
    "product_2_price" : "4567",
  },
  {
    "output_file_name" : "kuba-d123-plsa",
    "logo_url" : RCV("http://www.coo8.com/product/201251.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2D1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "三星 40英寸LED液晶电视",
    "product_0_url" : RCV("http://www.coo8.com/product/201251.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2D1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D1.png",
    "product_0_price" : "3598",
    "product_1_name" : "夏普 52英寸LED液晶电视 黑色",
    "product_1_url" : RCV("http://www.coo8.com/product/125618.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2D2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D2.png",
    "product_1_price" : "6888",
    "product_2_name" : "康佳32英寸蓝光LED液晶电视",
    "product_2_url" : RCV("http://www.coo8.com/product/191527.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2D3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/D3.png",
    "product_2_price" : "1798",
  },
  {
    "output_file_name" : "kuba-e123-plsa",
    "logo_url" : RCV("http://www.coo8.com/product/133194.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2E1"),
    "logo_image_url" : KUBA_LOGO_URL,
    "product_0_name" : "伊莱克斯静雅 挂式空调 白色",
    "product_0_url" : RCV("http://www.coo8.com/product/133194.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2E1"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E1.png",
    "product_0_price" : "1899",
    "product_1_name" : "奥克斯智家能系列柜式定频空调",
    "product_1_url" : RCV("http://www.coo8.com/product/180868.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2E2"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E2.png",
    "product_1_price" : "4999",
    "product_2_name" : "格力U酷系列挂式变频空调 银色",
    "product_2_url" : RCV("http://www.coo8.com/product/130088.html?utm_source=baidu&utm_medium=juejin&utm_campaign=duolian2E3"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/kuba/test/E3.png",
    "product_2_price" : "3599",
  },
  # fanke - query
  {
    "output_file_name" : "fanke-a123-query",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "短袖印花T恤 Victors 淡绿色",
    "product_0_url" : RCV("http://item.vt.vancl.com/0041835.html?source=bdjj-test-21ec0a39cdc99c1a"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A1.png",
    "product_0_price" : "29",
    "product_1_name" : "短袖印花T恤 Scarecrow",
    "product_1_url" : RCV("http://item.vt.vancl.com/0049968.html?source=bdjj-test-8badb9c41da62311"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A2.png",
    "product_1_price" : "29",
    "product_2_name" : "短袖印花T恤 咖啡精灵 浅桃色",
    "product_2_url" : RCV("http://item.vt.vancl.com/0168571.html?source=bdjj-test-394e71e83c1015af"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A3.png",
    "product_2_price" : "39",
  },
  {
    "output_file_name" : "fanke-b124-query",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "Street culture舒适系带帆布鞋",
    "product_0_url" : RCV("http://item.vancl.com/0167314.html?source=bdjj-test-967b1f9ebf4af685"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B1.jpg",
    "product_0_price" : "69",
    "product_1_name" : "伦敦字母涂鸦男子低帮帆布鞋",
    "product_1_url" : RCV("http://item.vancl.com/0166691.html?source=bdjj-test-7992af15f1cf6096"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B2.jpg",
    "product_1_price" : "79",
    "product_2_name" : "伦敦字母涂鸦女子低帮帆布鞋",
    "product_2_url" : RCV("http://item.vancl.com/0166714.html?source=bdjj-test-646f4676edb12bde"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B4.jpg",
    "product_2_price" : "75",
  },
  {
    "output_file_name" : "fanke-c134-query",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "中度洗水标准五分牛仔裤 灰色",
    "product_0_url" : RCV("http://item.vancl.com/0172169.html?source=bdjj-test-2a8edb34f5abca94"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C1.png",
    "product_0_price" : "119",
    "product_1_name" : "中度洗水牛仔热裤 浅蓝色",
    "product_1_url" : RCV("http://item.vancl.com/0172253.html?source=bdjj-test-db660c3b900149b5"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C3.jpg",
    "product_1_price" : "79",
    "product_2_name" : "经典洗水修身牛仔短裤 牛仔蓝",
    "product_2_url" : RCV("http://item.vancl.com/0174397.html?source=bdjj-test-b4991cc9061c4ac2"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C4.jpg",
    "product_2_price" : "79",
  },
  {
    "output_file_name" : "fanke-d234-query",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "经典舒适纯色人字拖 咖啡色",
    "product_0_url" : RCV("http://item.vancl.com/0177098.html?source=bdjj-test-ac9751ea8d15459d"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D2.jpg",
    "product_0_price" : "99",
    "product_1_name" : "磨砂牛皮帆船鞋 粉红色",
    "product_1_url" : RCV("http://item.vancl.com/0166620.html?source=bdjj-test-e1d67b744eee2d22"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D3.jpg",
    "product_1_price" : "199",
    "product_2_name" : "织带人字拖-航海风 红蓝白色",
    "product_2_url" : RCV("http://item.vancl.com/0038233.html?source=bdjj-test-980a7756816da597"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D4.jpg",
    "product_2_price" : "47",
  },
  # fanke - plsa
  {
    "output_file_name" : "fanke-a123-plsa",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "短袖印花T恤 Victors 淡绿色",
    "product_0_url" : RCV("http://item.vt.vancl.com/0041835.html?source=bdjj-test-9102ee7704d48444"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A1.png",
    "product_0_price" : "29",
    "product_1_name" : "短袖印花T恤 Scarecrow",
    "product_1_url" : RCV("http://item.vt.vancl.com/0049968.html?source=bdjj-test-d6fd1aec2c12ad3c"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A2.png",
    "product_1_price" : "29",
    "product_2_name" : "短袖印花T恤 咖啡精灵 浅桃色",
    "product_2_url" : RCV("http://item.vt.vancl.com/0168571.html?source=bdjj-test-4be2120d1b2a2f3e"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/A3.png",
    "product_2_price" : "39",
  },
  {
    "output_file_name" : "fanke-b124-plsa",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "Street culture舒适系带帆布鞋",
    "product_0_url" : RCV("http://item.vancl.com/0167314.html?source=bdjj-test-9bc31c716dfe45c8"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B1.jpg",
    "product_0_price" : "69",
    "product_1_name" : "伦敦字母涂鸦男子低帮帆布鞋",
    "product_1_url" : RCV("http://item.vancl.com/0166691.html?source=bdjj-test-8bd8e73d8da88cc4"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B2.jpg",
    "product_1_price" : "79",
    "product_2_name" : "伦敦字母涂鸦女子低帮帆布鞋",
    "product_2_url" : RCV("http://item.vancl.com/0166714.html?source=bdjj-test-c3c47e0584788bff"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/B4.jpg",
    "product_2_price" : "75",
  },
  {
    "output_file_name" : "fanke-c134-plsa",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "中度洗水标准五分牛仔裤 灰色",
    "product_0_url" : RCV("http://item.vancl.com/0172169.html?source=bdjj-test-9ed10121661dc905"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C1.png",
    "product_0_price" : "119",
    "product_1_name" : "中度洗水牛仔热裤 浅蓝色",
    "product_1_url" : RCV("http://item.vancl.com/0172253.html?source=bdjj-test-dafb34c66fcf47a1"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C3.jpg",
    "product_1_price" : "79",
    "product_2_name" : "经典洗水修身牛仔短裤 牛仔蓝",
    "product_2_url" : RCV("http://item.vancl.com/0174397.html?source=bdjj-test-a2914b7b1862fa9d"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/C4.jpg",
    "product_2_price" : "79",
  },
  {
    "output_file_name" : "fanke-d234-plsa",
    "logo_url" : RCV("http://www.vancl.com/"),
    "logo_image_url" : FANKE_LOGO_URL,
    "product_0_name" : "经典舒适纯色人字拖 咖啡色",
    "product_0_url" : RCV("http://item.vancl.com/0177098.html?source=bdjj-test-778fb3c3583688d0"),
    "product_0_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D2.jpg",
    "product_0_price" : "99",
    "product_1_name" : "磨砂牛皮帆船鞋 粉红色",
    "product_1_url" : RCV("http://item.vancl.com/0166620.html?source=bdjj-test-50a8a3156997c187"),
    "product_1_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D3.jpg",
    "product_1_price" : "199",
    "product_2_name" : "织带人字拖-航海风 红蓝白色",
    "product_2_url" : RCV("http://item.vancl.com/0038233.html?source=bdjj-test-7a50a0a6155c950c"),
    "product_2_image_url" : "http://eiv.baidu.com/juejin/vancl/test/D4.jpg",
    "product_2_price" : "47",
  },
];

def gen_code(tpl, data):
  for item in data:
    open(item['output_file_name'] + '.html', 'w').write(tpl % item)

def main():
  usage = 'usage: %prog [options] arg'
  parser = optparse.OptionParser(usage)

  parser.add_option('--tpl',
                    dest='tpl',
                    action='store',
                    help="tpl file name")
  (options, args) = parser.parse_args()
  if options.tpl:
    gen_code(open(options.tpl, 'rb').read(), DATA)
  else:
    parser.print_help()

if __name__ == "__main__":
  main()


